import type { NextPage } from "next";
import Head from "next/head";
import { useAuth } from "@clerk/nextjs";
import { Hero } from "../components/marketing/hero";
import { Features } from "../components/marketing/features";
import { Pricing } from "../components/marketing/pricing";
import { Header } from "../components/marketing/header";
import { useRouter } from "next/router";

const Index: NextPage = () => {
  const { isSignedIn } = useAuth();
  const router = useRouter();

  if (isSignedIn) {
    router.push("/track");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <Features />
        <Pricing />
      </main>
    </>
  );
};

export default Index;
