import { useAuth } from "@clerk/nextjs";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import { Login } from "../components/login";

const Settings: NextPage = () => {
  const { isSignedIn } = useAuth();

  if (!isSignedIn) {
    return <Login />;
  }
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="flex h-screen flex-col items-center">
          <div className="container grid grid-cols-1 gap-4">
            <h1>Settings</h1>
          </div>
        </main>
      </Layout>
    </>
  );
};

export default Settings;
