import { ReactNode } from "react";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Track",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Analytics />
    </html>
  );
}
